name: "Susana & Anselm's Wedding"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49224
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#444952'
    - '#7c8492'
    - '#69043b'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
