name: "Susana & Anselm's Wedding"
favicon: null
layout_spectrum: 0.18634557840414345
typography_spectrum: 0.25363648356869817
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6620480439160019
  lightness: 0.401202498935163
  saturation: 0.30014091543853283
  rhythmicContrast: 0.5770461326465011
purpose: []
